apiVersion: apis.apps.tanzu.vmware.com/v1alpha1
kind: APIDescriptor
metadata:
  name: where-for-dinner-availability
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"carto.run/v1alpha1","kind":"Workload","metadata":{"annotations":{},"labels":{"apis.apps.tanzu.vmware.com/register-api":"true","app.kubernetes.io/part-of":"where-for-dinner-availability","apps.tanzu.vmware.com/auto-configure-actuators":"true","apps.tanzu.vmware.com/has-tests":"true","apps.tanzu.vmware.com/workload-type":"web","networking.knative.dev/visibility":"cluster-local"},"name":"where-for-dinner-availability","namespace":"tanzu-workload"},"spec":{"build":{"env":[{"name":"BP_JVM_VERSION","value":"17"}]},"env":[{"name":"spring_profiles_active","value":"rabbitmq"}],"params":[{"name":"gitops_server_address","value":"https://github.com/"},{"name":"gitops_repository_owner","value":"kirtiapte"},{"name":"gitops_repository_name","value":"where-for-dinner"},{"name":"gitops_server_kind","value":"github"},{"name":"gitops_commit_branch","value":"origin/main"},{"name":"gitops_pull_request_title","value":"ready for review"},{"name":"gitops_pull_request_body","value":"generated by supply chain"},{"name":"testing_pipeline_matching_labels","value":{"apps.tanzu.vmware.com/language":"java","apps.tanzu.vmware.com/pipeline":"test"}},{"name":"annotations","value":{"autoscaling.knative.dev/maxScale":"4","autoscaling.knative.dev/minScale":"1","autoscaling.knative.dev/target":"200"}},{"name":"api_descriptor","value":{"description":"Core Where For Dinner service for retrieving dining availability","location":{"path":"/v3/api-docs"},"owner":"where-for-dinner-team","system":"where-for-dinner","type":"openapi"}}],"resources":{"limits":{"cpu":"1.5","memory":"750M"},"requests":{"cpu":"100m","memory":"500M"}},"serviceClaims":[{"name":"rmq","ref":{"apiVersion":"services.apps.tanzu.vmware.com/v1alpha1","kind":"ClassClaim","name":"msgbroker-where-for-dinner"}}],"source":{"git":{"ref":{"branch":"main"},"url":"https://github.com/kirtiapte/where-for-dinner"},"subPath":"where-for-dinner-availability"}}}
    autoscaling.knative.dev/maxScale: "4"
    autoscaling.knative.dev/minScale: "1"
    autoscaling.knative.dev/target: "200"
  labels:
    apis.apps.tanzu.vmware.com/register-api: "true"
    app.kubernetes.io/part-of: where-for-dinner-availability
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    networking.knative.dev/visibility: cluster-local
    app.kubernetes.io/component: run
    carto.run/workload-name: where-for-dinner-availability
spec:
  type: openapi
  description: Core Where For Dinner service for retrieving dining availability
  system: where-for-dinner
  owner: where-for-dinner-team
  location:
    path: /v3/api-docs
    baseURL:
      ref:
        apiVersion: serving.knative.dev/v1
        kind: Service
        name: where-for-dinner-availability

